(()=>{
const D={};
const add=(ru,tr,en)=>D[ru]={tr,en};
[
['Услуги','Hizmetler','Services'],['Как это работает','Nasıl çalışır','How it works'],['Специалисты','Uzmanlar','Professionals'],['Мои заказы','Siparişlerim','My requests'],['Войти','Giriş yap','Sign in'],['Я — специалист','Ben uzmanım','I’m a professional'],
['Подбор специалистов в Алании','Alanya’da uzman eşleştirme','Professional matching in Alanya'],['Напишите, что нужно сделать,','Ne yapılması gerektiğini yazın,','Tell us what you need,'],['а мы найдём лучшего мастера','size en iyi uzmanı bulalım','and we’ll find the best professional'],['Ответьте на несколько вопросов — мы подберём подходящих специалистов. Быстро и бесплатно.','Birkaç soruyu yanıtlayın, size uygun uzmanları bulalım. Hızlı ve ücretsiz.','Answer a few questions and we’ll match you with suitable professionals. Fast and free.'],['Какая услуга вам нужна?','Hangi hizmete ihtiyacınız var?','What service do you need?'],['Подобрать специалиста','Uzman bul','Find a professional'],['Часто ищут:','Popüler aramalar:','Popular searches:'],['Уборка','Temizlik','Cleaning'],['Ремонт техники','Cihaz tamiri','Appliance repair'],['Репетитор','Özel ders','Tutor'],['по отзывам клиентов','müşteri yorumlarına göre','based on customer reviews'],
['КАТЕГОРИИ УСЛУГ','HİZMET KATEGORİLERİ','SERVICE CATEGORIES'],['Популярные услуги','Popüler hizmetler','Popular services'],['Все услуги','Tüm hizmetler','All services'],['Ремонт и строительство','Tadilat ve inşaat','Renovation & construction'],['Красота и здоровье','Güzellik ve sağlık','Beauty & wellness'],['Уборка и помощь по дому','Temizlik ve ev yardımı','Cleaning & home help'],['Репетиторы и обучение','Özel ders ve eğitim','Tutoring & education'],['Фото и мероприятия','Fotoğraf ve etkinlik','Photo & events'],['Переводы и документы','Çeviri ve belgeler','Translation & documents'],['Автоуслуги','Oto hizmetleri','Auto services'],
['БЫСТРО И БЕЗОПАСНО','HIZLI VE GÜVENLİ','FAST AND SECURE'],['От задачи до результата —','Talebinizden sonuca','From request to result —'],['три простых шага','üç kolay adım','three simple steps'],['Вы выбираете не вслепую: сравнивайте предложения, отзывы и примеры работ.','Teklifleri, yorumları ve iş örneklerini karşılaştırarak seçim yapın.','Compare offers, reviews and work samples before choosing.'],['Расскажите о задаче','İhtiyacınızı anlatın','Describe your request'],['Ответьте на несколько вопросов — это займёт 2 минуты.','Birkaç soruyu yanıtlayın — yalnızca 2 dakika.','Answer a few questions — it takes 2 minutes.'],['Получите предложения','Teklifleri alın','Receive offers'],['Специалисты откликнутся с ценой и удобным временем.','Uzmanlar fiyat ve uygun zamanla yanıt verir.','Professionals reply with a price and available time.'],['Выберите лучшего','En uygun uzmanı seçin','Choose the best match'],['Смотрите рейтинг, отзывы и общайтесь напрямую.','Puanları ve yorumları inceleyin, doğrudan iletişim kurun.','Check ratings and reviews, then chat directly.'],
['СПЕЦИАЛИСТЫ АЛАНИИ','ALANYA UZMANLARI','ALANYA PROFESSIONALS'],['Специалисты рядом','Yakındaki uzmanlar','Professionals nearby'],['Выбрать','Seç','Choose'],['Анкета','Profil','Profile'],['Ремонт','Tamir','Repairs'],['Красота','Güzellik','Beauty'],['Обучение','Eğitim','Education'],
['USTA ALANYA ДЛЯ СПЕЦИАЛИСТОВ','UZMANLAR İÇİN USTA ALANYA','USTA ALANYA FOR PROFESSIONALS'],['Сайт для специалистов.','Uzmanlar için platform.','A platform for professionals.'],['Находите клиентов рядом.','Yakınınızdaki müşterilere ulaşın.','Find customers nearby.'],['Создайте профиль бесплатно и получайте подходящие заказы в Алании.','Ücretsiz profil oluşturun ve Alanya’daki uygun işleri alın.','Create a free profile and receive suitable jobs in Alanya.'],['Новый заказ рядом','Yakında yeni iş','New job nearby'],['Откликнуться','Teklif ver','Respond'],['Местные специалисты для любых задач','Her iş için yerel uzmanlar','Local professionals for every task'],['Клиентам','Müşteriler','Customers'],['Специалистам','Uzmanlar','Professionals'],['Конфиденциальность','Gizlilik','Privacy'],['Жалобы','Şikâyetler','Complaints'],['Демонстрационная версия.','Demo sürümü.','Demo version.'],
['Найдём специалиста','Bir uzman bulalım','We’ll find a professional'],['Опишите задачу, и подходящие мастера предложат цену.','İhtiyacınızı anlatın, uygun uzmanlar fiyat teklif etsin.','Describe the task and suitable professionals will quote a price.'],['Услуга','Hizmet','Service'],['Ваш район','Bölgeniz','Your district'],['Телефон','Telefon','Phone'],['Продолжить →','Devam →','Continue →'],['Заявка создана!','Talep oluşturuldu!','Request created!'],
['Услуги','Hizmetler','Services'],['Заказы','Talepler','Requests'],['Чаты','Mesajlar','Chats'],['Избранное','Favoriler','Favorites'],['Профиль','Profil','Profile'],['Все услуги','Tüm hizmetler','All services'],['Поиск по 1200 услугам','1200 hizmette ara','Search 1,200 services'],
['Активные','Aktif','Active'],['Завершённые','Tamamlanan','Completed'],['Черновики','Taslaklar','Drafts'],['Смотреть отклики','Teklifleri gör','View responses'],['Изменить','Düzenle','Edit'],['Написать','Mesaj gönder','Message'],['Детали заказа','Talep ayrıntıları','Request details'],['+ Создать новый заказ','+ Yeni talep oluştur','+ Create a new request'],
['Сообщения','Mesajlar','Messages'],['Общайтесь внутри Usta Alanya','Usta Alanya içinde iletişim kurun','Chat inside Usta Alanya'],['Чат доступен до и после выбора специалиста. Контактами можно обменяться по желанию.','Uzman seçiminden önce ve sonra sohbet edebilirsiniz. İsterseniz iletişim bilgilerinizi paylaşabilirsiniz.','Chat is available before and after choosing a professional. Sharing contact details is optional.'],['Все','Tümü','All'],['Непрочитанные','Okunmamış','Unread'],
['Пока никого нет','Henüz kimse yok','No one here yet'],['Добавляйте специалистов в избранное, чтобы не потерять.','Uzmanları daha sonra bulmak için favorilere ekleyin.','Save professionals to your favorites for later.'],['Найти специалиста','Uzman bul','Find a professional'],['Личный кабинет','Hesabım','My account'],['Ваш профиль','Profiliniz','Your profile'],['Настройки','Ayarlar','Settings'],['Поддержка','Destek','Support'],
['Новый заказ','Yeni talep','New request'],['Какая услуга нужна?','Hangi hizmet gerekli?','What service is needed?'],['Где выполнить работу?','İş nerede yapılacak?','Where should the work be done?'],['Когда вам удобно?','Ne zaman uygunsunuz?','When is convenient?'],['Проверьте заказ','Talebi kontrol edin','Review request'],['Как можно скорее','En kısa sürede','As soon as possible'],['В ближайшие дни','Önümüzdeki günlerde','In the next few days'],['В выходные','Hafta sonu','On the weekend'],['Выбрать дату','Tarih seç','Choose a date'],['Дистанционно','Uzaktan','Remote'],['Опубликовать заказ','Talebi yayınla','Publish request'],['Отмена','İptal','Cancel'],['← Назад','← Geri','← Back'],
['ДЛЯ СПЕЦИАЛИСТОВ','UZMANLAR İÇİN','FOR PROFESSIONALS'],['Ваши отличные навыки кому-то рядом сейчас очень нужны','Harika becerilerinize yakınınızdaki birinin şu anda ihtiyacı var','Someone nearby needs your excellent skills right now'],['Заполните короткую анкету — мы покажем подходящие заказы клиентов в Алании.','Kısa formu doldurun; Alanya’daki uygun müşteri taleplerini gösterelim.','Complete a short form and we’ll show suitable customer requests in Alanya.'],['Какие услуги вы оказываете?','Hangi hizmetleri veriyorsunuz?','What services do you provide?'],['Где вы готовы работать?','Nerelerde çalışabilirsiniz?','Where can you work?'],['Расскажите об опыте','Deneyiminizi anlatın','Tell us about your experience'],['Создайте профиль','Profilinizi oluşturun','Create your profile'],['Анкета отправлена','Profil gönderildi','Profile submitted'],['Можно выбрать несколько направлений.','Birden fazla hizmet seçebilirsiniz.','You can select multiple services.'],['Найти услугу','Hizmet ara','Find a service'],['Выберите один или несколько районов.','Bir veya daha fazla bölge seçin.','Select one or more districts.'],['Эта информация поможет клиентам выбрать вас.','Bu bilgiler müşterilerin sizi seçmesine yardımcı olur.','This information helps customers choose you.'],['О себе','Hakkınızda','About you'],['Имя и фамилия','Ad ve soyad','Full name'],['Контакты не публикуются без вашего согласия.','İletişim bilgileriniz izniniz olmadan yayınlanmaz.','Your contact details are not published without your consent.'],['Отправить анкету','Profili gönder','Submit profile'],['Заявка специалиста создана!','Uzman başvurusu oluşturuldu!','Professional application created!'],['Что будет дальше','Sonraki adımlar','What happens next'],['Посмотреть пример заказов','Örnek işleri görüntüle','View sample jobs'],
['Правовые документы','Yasal belgeler','Legal documents'],['Условия для клиентов','Müşteri koşulları','Customer terms'],['Правила специалистов','Uzman kuralları','Professional rules'],['Согласие на обработку','Veri işleme onayı','Data processing consent'],['Отзывы','Yorumlar','Reviews'],['Жалобы и споры','Şikâyetler ve uyuşmazlıklar','Complaints & disputes'],['Хранение и удаление','Saklama ve silme','Retention & deletion'],['Иностранные пользователи','Yabancı kullanıcılar','Foreign users'],['← На главную','← Ana sayfa','← Home'],['ПРАВОВЫЕ ДОКУМЕНТЫ','YASAL BELGELER','LEGAL DOCUMENTS'],['Правила Usta Alanya','Usta Alanya Kuralları','Usta Alanya Rules'],['Черновик для юридической проверки','Hukuki inceleme taslağı','Draft for legal review'],
['Cookies на Usta Alanya','Usta Alanya çerezleri','Cookies on Usta Alanya'],['Необходимые cookies обеспечивают вход и безопасность. Аналитические используются только с вашего согласия.','Zorunlu çerezler giriş ve güvenliği sağlar. Analitik çerezler yalnızca onayınızla kullanılır.','Essential cookies enable sign-in and security. Analytics cookies are used only with your consent.'],['Подробнее','Daha fazla bilgi','Learn more'],['Только необходимые','Yalnızca zorunlu','Essential only'],['Принять','Kabul et','Accept']
].forEach(x=>add(...x));

const serviceRows=[
['Сантехник','Tesisatçı','Plumber'],['Электрик','Elektrikçi','Electrician'],['Мастер на час','Tamir ustası','Handyman'],['Ремонт квартир','Ev tadilatı','Apartment renovation'],['Укладка плитки','Fayans döşeme','Tile installation'],['Малярные работы','Boya işleri','Painting'],['Штукатурка','Sıva işleri','Plastering'],['Сборка мебели','Mobilya montajı','Furniture assembly'],['Установка дверей','Kapı montajı','Door installation'],['Ремонт крыши','Çatı tamiri','Roof repair'],['Сварочные работы','Kaynak işleri','Welding'],
['Климат и бассейны','Klima ve havuz','Climate & pools'],['Установка кондиционеров','Klima montajı','AC installation'],['Ремонт кондиционеров','Klima tamiri','AC repair'],['Чистка кондиционеров','Klima temizliği','AC cleaning'],['Вентиляция','Havalandırma','Ventilation'],['Обслуживание бассейнов','Havuz bakımı','Pool maintenance'],['Ремонт насосов','Pompa tamiri','Pump repair'],['Солнечные панели','Güneş panelleri','Solar panels'],
['Парикмахер','Kuaför','Hairdresser'],['Окрашивание волос','Saç boyama','Hair coloring'],['Маникюр и педикюр','Manikür ve pedikür','Manicure & pedicure'],['Массаж','Masaj','Massage'],['Косметолог','Güzellik uzmanı','Cosmetologist'],['Визажист','Makyaj uzmanı','Makeup artist'],['Бровист','Kaş uzmanı','Brow artist'],['Персональный тренер','Kişisel antrenör','Personal trainer'],['Йога','Yoga','Yoga'],['Диетолог','Diyetisyen','Dietitian'],
['Обучение и репетиторы','Eğitim ve özel ders','Education & tutoring'],['Турецкий язык','Türkçe','Turkish'],['Русский язык','Rusça','Russian'],['Английский язык','İngilizce','English'],['Математика','Matematik','Mathematics'],['Музыка','Müzik','Music'],['Подготовка к школе','Okula hazırlık','School preparation'],['Шахматы','Satranç','Chess'],['Рисование','Resim','Drawing'],['Компьютерная грамотность','Bilgisayar eğitimi','Computer literacy'],
['Дом и быт','Ev ve günlük yaşam','Home & household'],['Уборка квартир','Ev temizliği','Apartment cleaning'],['Уборка вилл','Villa temizliği','Villa cleaning'],['Уборка после ремонта','Tadilat sonrası temizlik','Post-renovation cleaning'],['Химчистка мебели','Mobilya temizliği','Upholstery cleaning'],['Мытьё окон','Cam temizliği','Window cleaning'],['Садовник','Bahçıvan','Gardener'],['Няня','Bebek bakıcısı','Babysitter'],['Сиделка','Hasta bakıcı','Caregiver'],['Помощник по хозяйству','Ev yardımcısı','Household helper'],['Выгул собак','Köpek gezdirme','Dog walking'],['Дезинсекция','Haşere kontrolü','Pest control'],
['Техника и компьютеры','Teknik ve bilgisayar','Tech & computers'],['Ремонт телефонов','Telefon tamiri','Phone repair'],['Ремонт бытовой техники','Beyaz eşya tamiri','Appliance repair'],['Ремонт телевизоров','Televizyon tamiri','TV repair'],['Компьютерная помощь','Bilgisayar desteği','Computer support'],['Настройка Wi-Fi','Wi-Fi kurulumu','Wi-Fi setup'],['Умный дом','Akıllı ev','Smart home'],['Видеонаблюдение','Güvenlik kamerası','Video surveillance'],['Ремонт кофемашин','Kahve makinesi tamiri','Coffee machine repair'],
['Авто и перевозки','Oto ve ulaşım','Auto & transport'],['Автоэлектрик','Oto elektrikçi','Auto electrician'],['Шиномонтаж','Lastik servisi','Tire service'],['Диагностика автомобиля','Araç arıza tespiti','Car diagnostics'],['Трансфер в аэропорт','Havalimanı transferi','Airport transfer'],['Грузоперевозки','Nakliye','Freight transport'],['Курьер','Kurye','Courier'],['Эвакуатор','Çekici','Tow truck'],['Аренда авто с водителем','Şoförlü araç kiralama','Car with driver'],
['Документы и деловые услуги','Belge ve iş hizmetleri','Documents & business'],['Перевод документов','Belge çevirisi','Document translation'],['Устный переводчик','Sözlü tercüman','Interpreter'],['Юрист','Avukat','Lawyer'],['Миграционный консультант','Göç danışmanı','Immigration consultant'],['Бухгалтер','Muhasebeci','Accountant'],['Риелтор','Emlak danışmanı','Real estate agent'],['Страховой консультант','Sigorta danışmanı','Insurance consultant'],['Регистрация бизнеса','Şirket kuruluşu','Business registration'],
['Фото, события и творчество','Fotoğraf, etkinlik ve yaratıcılık','Photo, events & creative'],['Фотограф','Fotoğrafçı','Photographer'],['Видеограф','Videograf','Videographer'],['Организатор мероприятий','Etkinlik organizatörü','Event planner'],['Ведущий','Sunucu','Event host'],['Диджей','DJ','DJ'],['Декоратор','Dekoratör','Decorator'],['Кейтеринг','Catering','Catering'],['Аниматор','Animatör','Entertainer'],['Графический дизайнер','Grafik tasarımcı','Graphic designer'],
['Цифровые услуги','Dijital hizmetler','Digital services'],['Создание сайтов','Web sitesi geliştirme','Website development'],['Продвижение в соцсетях','Sosyal medya yönetimi','Social media promotion'],['Контекстная реклама','Dijital reklam','Paid search advertising'],['Копирайтер','Metin yazarı','Copywriter'],['Перевод сайтов','Web sitesi çevirisi','Website translation'],['Настройка CRM','CRM kurulumu','CRM setup'],['Онлайн-консультация','Online danışmanlık','Online consultation']];serviceRows.forEach(x=>add(...x));
const districts=[['Авсаллар','Avsallar','Avsallar'],['Центральный район','Alanya Merkez','Central Alanya'],['Махмутлар','Mahmutlar','Mahmutlar'],['Каргыджак','Kargıcak','Kargicak'],['Джикджилли','Cikcilli','Cikcilli'],['Демирташ','Demirtaş','Demirtas'],['Оба','Oba','Oba'],['Тосмур','Tosmur','Tosmur'],['Кестель','Kestel','Kestel'],['Кызылот','Kızılot','Kizilot'],['Окурджалар','Okurcalar','Okurcalar'],['Паяллар','Payallar','Payallar'],['Тюрклер','Türkler','Turkler'],['Инжекум','İncekum','Incekum'],['Конаклы','Konaklı','Konakli']];districts.forEach(x=>add(...x));
[['Например, установить кондиционер','Örneğin, klima montajı','For example, install an air conditioner'],['Например, починить кран','Örneğin, musluk tamiri','For example, repair a tap'],['Ваше имя','Adınız','Your name'],['Сообщение...','Mesaj...','Message...'],['Кратко расскажите о навыках и подходе к работе','Becerilerinizi ve çalışma yaklaşımınızı kısaca anlatın','Briefly describe your skills and approach']].forEach(x=>add(...x));
const requestedLang=new URLSearchParams(location.search).get('lang');
let lang=['ru','tr','en'].includes(requestedLang)?requestedLang:(localStorage.getItem('usta-lang')||'ru');
const trText=s=>{if(lang==='ru')return s;if(D[s])return D[s][lang];const m=s.match(/^([✓📍•+\d.\s←→]*)(.*)$/);return m&&D[m[2]]?m[1]+D[m[2]][lang]:s};
const translateNode=n=>{if(n.nodeType===3){const raw=n.nodeValue,trim=raw.trim();if(!trim)return;if(!n.__ru)n.__ru=trim;const out=trText(n.__ru);if(trim!==out)n.nodeValue=raw.replace(trim,out)}else if(n.nodeType===1){['placeholder','title','aria-label'].forEach(a=>{const v=n.getAttribute(a);if(!v)return;const k=`__ru_${a}`;if(!n[k])n[k]=v;const out=trText(n[k]);if(v!==out)n.setAttribute(a,out)});n.childNodes.forEach(translateNode)}};
const apply=()=>{document.documentElement.lang=lang;document.body&&translateNode(document.body);const s=document.querySelector('#langSelect');if(s&&s.value!==lang)s.value=lang;const titles={ru:'Usta Alanya — специалисты рядом',tr:'Usta Alanya — yakınınızdaki uzmanlar',en:'Usta Alanya — professionals nearby'};if(location.pathname.endsWith('/')||location.pathname.endsWith('index.html'))document.title=titles[lang]};
document.addEventListener('DOMContentLoaded',()=>{const s=document.querySelector('#langSelect');if(s)s.addEventListener('change',e=>{lang=e.target.value;localStorage.setItem('usta-lang',lang);apply()});apply();new MutationObserver(ms=>ms.forEach(m=>m.addedNodes.forEach(translateNode))).observe(document.body,{childList:true,subtree:true})});
})();
