const services=['Уборка квартиры','Ремонт и строительство','Ремонт кондиционеров','Ремонт бытовой техники','Репетитор турецкого языка','Маникюр и педикюр','Стрижка и окрашивание','Сантехник','Электрик','Перевод документов','Фотограф'];
const modal=document.querySelector('#modal'), taskInput=document.querySelector('#taskInput'), search=document.querySelector('#serviceSearch'), suggestions=document.querySelector('#suggestions');
function openModal(task='',type='task'){modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';document.querySelector('#requestForm').style.display='block';document.querySelector('#success').style.display='none';document.querySelector('#modalTitle').textContent=type==='pro'?'Начните получать заказы':type==='login'?'Вход в личный кабинет':'Найдём специалиста';document.querySelector('#modalText').textContent=type==='pro'?'Расскажите, какие услуги вы оказываете в Алании.':'Опишите задачу, и подходящие мастера предложат цену.';taskInput.value=task;setTimeout(()=>taskInput.focus(),100)}
function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}
document.querySelectorAll('[data-query]').forEach(el=>el.addEventListener('click',()=>openModal(el.dataset.query)));
document.querySelectorAll('[data-name]').forEach(el=>el.addEventListener('click',()=>openModal('Связаться со специалистом '+el.dataset.name)));
document.querySelectorAll('[data-modal]').forEach(el=>el.addEventListener('click',()=>openModal('',el.dataset.modal)));
document.querySelector('#closeModal').addEventListener('click',closeModal);modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
document.querySelector('#searchForm').addEventListener('submit',e=>{e.preventDefault();openModal(search.value)});
search.addEventListener('input',()=>{const q=search.value.toLowerCase();const found=services.filter(s=>s.toLowerCase().includes(q)).slice(0,5);suggestions.innerHTML=found.map(s=>`<button type="button">${s}</button>`).join('');suggestions.style.display=q&&found.length?'block':'none';suggestions.querySelectorAll('button').forEach(b=>b.onclick=()=>{search.value=b.textContent;suggestions.style.display='none';openModal(b.textContent)})});
document.querySelector('#requestForm').addEventListener('submit',e=>{e.preventDefault();e.currentTarget.style.display='none';document.querySelector('#success').style.display='block'});
const toast=document.querySelector('#toast');
document.querySelector('.menu-toggle').addEventListener('click',()=>{document.querySelector('.header-actions').style.display=document.querySelector('.header-actions').style.display==='flex'?'none':'flex'});
const track=document.querySelector('#expertTrack');document.querySelector('#next').onclick=()=>track.scrollBy({left:290,behavior:'smooth'});document.querySelector('#prev').onclick=()=>track.scrollBy({left:-290,behavior:'smooth'});
